# Generated by Django 5.2.14 on 2026-05-30 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(blank=True, choices=[('drinks', 'Drinks'), ('food', 'Food'), ('snacks', 'Snacks'), ('transport', 'Transport'), ('fun', 'Fun'), ('university', 'University'), ('groceries', 'Groceries'), ('forgot', 'Forgot'), ('others', 'Others')], max_length=20, null=True)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Account')], default='cash', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]