# Generated by Django 5.2.12 on 2026-05-30 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_add_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_user_id_8af7f1_idx',
            old_name='transactio_user_id_ea37bd_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_user_id_4685bf_idx',
            old_name='transactio_user_id_1f1cb9_idx',
        ),
    ]